### ISSUE TITLE
gowno

### ISSUE THREAD

**Issue by sahejooo** [NoveTeam/Lighter#4]
nie poelcam

**Comment by sahejooo** [comment]
zapalniczka.discord

**Comment by sahejooo** [comment]
discord.zapalniczka XDDDDDDDDDDDDDDDDDDDDD

**Comment by sahejooo** [comment]
dsicord.py!!

**Comment by NjeHypereK** [comment]
ide grac w bobloxa i mama mi kupi bobuxy

**Comment by sahejooo** [comment]
bobux.zapalniczka
